### ISSUE TITLE
Provide temporary file storage

### ISSUE THREAD

**Issue by ZebraCanevra** [nokonoko/Pomf#11]
If I know my file is not going to be needed permanently, I should be able to specify a deletion time (hours/days/weeks/months).

For most of the files I share I don't want them to take up unnecessary space after I've forgotten about them. You probably already delete files after they aren't downloaded for a while, but to be able to specify an even shorter amount is always helpful to free up space.

An extension upon this temporary storage would be not to specify a deletion time, but rather something like a 4chan thread, and the file will be deleted after that thread 404s. This would be rather easy to check every hour by just using a HEAD request to save bandwidth. If the thread stays alive for longer than X days (e.g. threads on slow boards and/or stickies), then you stop checking the thread and just let the file stay there until it is deleted for inactivity.

**Comment by tengwar** [comment]
+1. Sometimes I need a file for few days only and I don't want to litter the server, but 1h (as on uguu.se) is often too short. You could have few default values, like pastebin: 10min, 1h, 1d, 1w, 2w, 1m.

**Comment by nokonoko** [comment]
I made uguu.se for this instead, I will up the storage time soon.
