### ISSUE TITLE
Grill not changing?

### ISSUE THREAD

**Issue by Shudouken** [nokonoko/Pomf#29]
I've had the same [grill](http://pomf.se/img/11.png) show up for the past 4 days, previously she used to change everytime I visited the site, is the randomizer broken, or was there something changed?
The code at [github](https://github.com/nokonoko/Pomf/blob/master/static/grill.php) doesn't mention numbers past 10, so I'm not really sure if it is the most recent version

(Also requesting more grills)

**Comment by nokonoko** [comment]
Do a hard cache reset on your browser and you should see a diff grill, works fine for me.

**Comment by Shudouken** [comment]
I tried that, and also tried using a different browser, and a different computer alltogether, all show the same girl as in my first post, should they change on every browser refresh?

**Comment by nokonoko** [comment]
Try now, think the CF cache was a bit to agressive.

**Comment by Shudouken** [comment]
Thanks, now it works perfectly
