### ISSUE TITLE
Pomf Paste: add more expiration options

### ISSUE THREAD

**Issue by JamesTheAwesomeDude** [nokonoko/Pomf#31]
Would it be possible to add "Week" and "6 Months" to p.pomf.se?

Even better would be something like Imgur uses, "3 months without views", but I understand that that would take some changes to the code.

**Comment by nokonoko** [comment]
I'll look into adding 1 week and 6 months, shouldn't take long.

**Comment by nokonoko** [comment]
There we go, should be working fine. Also do keep in mind that Pomf isn't imgur, X amount of time without someone viewing feels rather dumb to me and implies tracking my user to a small extent, also if you set a time for something to expire but want to keep it incase someone views it why not just set forever?

Of course it can be done without logging information about users but still, at this point I don't think it needs to be added. Maybe I'll add such a feature to Uguu which is temporary file hosting after all while Pomf is "forever".

**Comment by JamesTheAwesomeDude** [comment]
@nokonoko That feature would be REALLY useful for Uguu.se - 1 hour without downloads would be a quite sane time limit for large files.

**Comment by TheHowl** [comment]
Shouldn't this issue be on https://github.com/nokonoko/Uguu instead?

**Comment by JamesTheAwesomeDude** [comment]
@TheHowl yeah, it's not a full issue, just a passing comment in reponse to @nokonoko's mention of its potential utility there.

**Comment by JamesTheAwesomeDude** [comment]
Just reloaded the page, and it worked. The changes have filtered through all caches and made it to an end-user.
