### ISSUE TITLE
do files ever expire and get deleted?

### ISSUE THREAD

**Issue by gotquestions** [nokonoko/Pomf#37]
I am looking for a site where there is "never expire" and files are NOT DELETED.
Is there an expire of files?
Thankyou.

**Comment by avail** [comment]
they don't.

**Comment by gotquestions** [comment]
Oh great **thankyou very much** !!
Exactly what I was hoping for!
Would be helpful if you stated no expire or deletion on the page 
https://maxfile.ro/
under 
Max upload size is 50MiB!

Thankyou.

**Comment by avail** [comment]
Pomf is not related to maxfile. We don't know what they do, they're using the pomf source but aren't affilated with pomf.

**Comment by gotquestions** [comment]
Then what is your pomf url and I will check it out because there is no expire or deletion.
Thankyou

**Comment by nokonoko** [comment]
Pomf.se was the original "Pomf", it got shut down ~3 weeks ago due to money issues.

**Comment by NuckChorris** [comment]
Pomf itself is gone, maxfile runs the Pomf software

**Comment by gotquestions** [comment]
So confusing. so Pomf itself is gone, maxfile runs the Pomf software
but no support or contact for maxfile info if files get expired or deleted?

**Comment by avail** [comment]
Precisely.

**Comment by nokonoko** [comment]
@gotquestions as said before, Maxfile and others are not associated with Pomf.se (me), how others chose to modify the code is not something I can control.

**Comment by NuckChorris** [comment]
I doubt maxfile will delete or expire files though, since it runs this software

**Comment by gotquestions** [comment]
Yes I understand nokonoko thankyou.
Yes I doubt it too NuckChorris but need to be sure. Thanks for adding input NuckChorris and avail.
Maybe ShareX will know because they are the ones that led me to the site.

**Comment by TheHowl** [comment]
ShareX is not affiliated in *ANY WAY* to any upload service. They just 
use APIs of common ones and put them inside ShareX, but pretty much 
nothing else. Do not ask them, they'll probably tell you to go ask 
directly the owner of maxfile.

Il 05/07/2015 00:30, gotquestions ha scritto:

**Comment by alin1337** [comment]
No file expiration on maxfile.

I own it

**Comment by gotquestions** [comment]
Oh wow exactly what I need. NO FILE EXPIRATION on maxfile **thankyou very much** alin1337 !
Would be helpful to state that info somewhere under Max upload size is 50MiB! to be certain.
And I guess I have to trust that you alin1337 are actually the owner of the maxfile site as there is no contact link on there to prove that.
Thankyou for response !
